/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ChessEventTrigger, IntensityLevel } from '../types/audio';

export interface MyInstantsSoundButton {
  id: string;
  name: string;
  color: string;
  darkColor: string;
  category: 'popular' | 'reactions' | 'gaming' | 'brainrot' | 'music' | 'anime';
  soundUrl: string;
  fallbackUrl?: string;
  chessEvent: ChessEventTrigger;
  intensity: IntensityLevel;
  visualToast: string;
  description: string;
  playsCount: string;
}

// Exact sound buttons matching https://www.myinstants.com/en/search/?name=meme
// Real recorded audio clips ONLY - NO AI INBUILD audio
export const MYINSTANTS_MEME_BUTTONS: MyInstantsSoundButton[] = [
  {
    id: 'vine_boom',
    name: 'Vine Boom',
    color: '#e74c3c',
    darkColor: '#c0392b',
    category: 'popular',
    soundUrl: '/sounds/vine_boom.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/vine-boom.mp3',
    chessEvent: 'capture_rook',
    intensity: 3,
    visualToast: 'VINE BOOM 💥',
    description: 'The #1 most played sound effect on MyInstants',
    playsCount: '24.8M',
  },
  {
    id: 'bruh',
    name: 'Bruh Sound Effect #2',
    color: '#e67e22',
    darkColor: '#d35400',
    category: 'popular',
    soundUrl: '/sounds/bruh.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/bruh.mp3',
    chessEvent: 'capture_pawn',
    intensity: 2,
    visualToast: 'BRUH 🗿',
    description: 'Iconic Vine deep baritone reaction',
    playsCount: '18.1M',
  },
  {
    id: 'emotional_damage',
    name: 'Emotional Damage',
    color: '#3498db',
    darkColor: '#2980b9',
    category: 'popular',
    soundUrl: '/sounds/emotional_damage.mp3',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/emotional-damage-meme.mp3',
    chessEvent: 'blunder',
    intensity: 3,
    visualToast: 'EMOTIONAL DAMAGE! 💔',
    description: 'Steven He viral blunder reaction',
    playsCount: '19.4M',
  },
  {
    id: 'metal_pipe',
    name: 'Metal Pipe Falling',
    color: '#95a5a6',
    darkColor: '#7f8c8d',
    category: 'popular',
    soundUrl: '/sounds/metal_pipe.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/metal-pipe-clang.mp3',
    chessEvent: 'capture_queen',
    intensity: 3,
    visualToast: 'METAL PIPE DROP 🪙💥',
    description: 'Loud metallic reverberated pipe collision',
    playsCount: '16.7M',
  },
  {
    id: 'windows_xp_error',
    name: 'Windows XP Error',
    color: '#e74c3c',
    darkColor: '#c0392b',
    category: 'gaming',
    soundUrl: '/sounds/windows_xp_error.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/windows-xp-error.mp3',
    chessEvent: 'blunder',
    intensity: 2,
    visualToast: 'WINDOWS ERROR ❌',
    description: 'Iconic critical stop chord chime',
    playsCount: '12.4M',
  },
  {
    id: 'spongebob_fail',
    name: 'SpongeBob Fail (Womp Womp)',
    color: '#f1c40f',
    darkColor: '#f39c12',
    category: 'reactions',
    soundUrl: '/sounds/spongebob_fail.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/spongebob-fail.mp3',
    chessEvent: 'mistake',
    intensity: 2,
    visualToast: 'WOMP WOMP 🎺😭',
    description: 'Sliding brass disappointment trombone',
    playsCount: '11.7M',
  },
  {
    id: 'minecraft_hurt',
    name: 'Minecraft Hurt (Classic Oof)',
    color: '#8e44ad',
    darkColor: '#7d3c98',
    category: 'gaming',
    soundUrl: '/sounds/minecraft_hurt.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/classic_hurt.mp3',
    chessEvent: 'capture_pawn',
    intensity: 2,
    visualToast: 'MINECRAFT OOF 🟩',
    description: 'Retro wooden bone snap punch impact',
    playsCount: '14.8M',
  },
  {
    id: 'fah',
    name: 'FAH 💨',
    color: '#7f8c8d',
    darkColor: '#626567',
    category: 'reactions',
    soundUrl: '/sounds/fah.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/fah.mp3',
    chessEvent: 'capture_pawn',
    intensity: 1,
    visualToast: 'FAH 💨',
    description: 'Airy breath vocal whoosh',
    playsCount: '8.1M',
  },
  {
    id: 'omg_hell_nah',
    name: 'Hell Nah (AH HELL NAW)',
    color: '#e74c3c',
    darkColor: '#c0392b',
    category: 'reactions',
    soundUrl: '/sounds/omg_hell_nah.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/hell-nah-sound-effect.mp3',
    chessEvent: 'catastrophic_blunder',
    intensity: 3,
    visualToast: 'AH HELL NAH 💀',
    description: 'Classic loud shocked vocal reaction',
    playsCount: '15.1M',
  },
  {
    id: 'anime_wow',
    name: 'Anime WOW Sound',
    color: '#e91e63',
    darkColor: '#c2185b',
    category: 'anime',
    soundUrl: '/sounds/anime_wow.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/anime-wow-sound-effect.mp3',
    chessEvent: 'brilliant',
    intensity: 2,
    visualToast: 'WOW! 🌸✨',
    description: 'Fairy Tail happy sparkly anime reaction',
    playsCount: '16.4M',
  },
  {
    id: 'sanctuary_guardian_what',
    name: 'WHAT (Sanctuary Guardian)',
    color: '#3498db',
    darkColor: '#2980b9',
    category: 'popular',
    soundUrl: '/sounds/sanctuary_guardian_what.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/what-sanctuary-guardian.mp3',
    chessEvent: 'inaccuracy',
    intensity: 2,
    visualToast: 'WHAT?! ❓🤨',
    description: 'Earthbound Sanctuary Guardian opening beat',
    playsCount: '13.9M',
  },
  {
    id: 'bone_crack',
    name: 'Bone Crack / Roblox Snap',
    color: '#d35400',
    darkColor: '#ba4a00',
    category: 'gaming',
    soundUrl: '/sounds/bone_crack.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/bone-crack.mp3',
    chessEvent: 'capture_minor',
    intensity: 2,
    visualToast: 'CRACK! 🦴💥',
    description: 'Crunchy bone snap impact sound',
    playsCount: '9.4M',
  },
  {
    id: 'dramatic_boomer',
    name: 'Dramatic Boom Stinger',
    color: '#8e44ad',
    darkColor: '#7d3c98',
    category: 'music',
    soundUrl: '/sounds/dramatic_boomer.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/dramatic-sound-effect.mp3',
    chessEvent: 'check',
    intensity: 3,
    visualToast: 'DUN DUN DUN 🥁',
    description: 'Intense cinematic orchestral stinger',
    playsCount: '11.8M',
  },
  {
    id: 'ding',
    name: 'Ding Sound Effect',
    color: '#f1c40f',
    darkColor: '#f39c12',
    category: 'popular',
    soundUrl: '/sounds/ding.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/ding-sound-effect_2.mp3',
    chessEvent: 'move_piece',
    intensity: 1,
    visualToast: 'DING! 💡',
    description: 'Crisp bright bell ding',
    playsCount: '14.2M',
  },
  {
    id: 'wilhelm_scream',
    name: 'Wilhelm Scream',
    color: '#e74c3c',
    darkColor: '#c0392b',
    category: 'reactions',
    soundUrl: '/sounds/wilhelm_scream.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/wilhelm-scream.mp3',
    chessEvent: 'queen_lost',
    intensity: 4,
    visualToast: 'AAAAAHHH 😱',
    description: 'The most legendary movie scream in cinema history',
    playsCount: '17.3M',
  },
  {
    id: 'oh_my_god_vine',
    name: 'Oh My God (Vine)',
    color: '#e67e22',
    darkColor: '#d35400',
    category: 'reactions',
    soundUrl: '/sounds/oh_my_god_vine.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/oh-my-god-vine.mp3',
    chessEvent: 'blunder',
    intensity: 3,
    visualToast: 'OH MY GOD! 😲',
    description: 'Surprised viral Vine exclamation',
    playsCount: '12.0M',
  },
  {
    id: 'illuminati_confirmed',
    name: 'Illuminati Confirmed (X-Files)',
    color: '#2ecc71',
    darkColor: '#27ae60',
    category: 'music',
    soundUrl: '/sounds/illuminati_confirmed.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/illuminati-confirmed.mp3',
    chessEvent: 'fork',
    intensity: 2,
    visualToast: 'ILLUMINATI 👁️🔺',
    description: 'Mystery X-Files whistle theme',
    playsCount: '10.7M',
  },
  {
    id: 'triggered',
    name: 'Triggered (Meme SFX)',
    color: '#c0392b',
    darkColor: '#962d22',
    category: 'reactions',
    soundUrl: '/sounds/triggered.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/triggered.mp3',
    chessEvent: 'blunder',
    intensity: 3,
    visualToast: 'TRIGGERED 🔴💢',
    description: 'Dramatic bass pulse warning sound',
    playsCount: '8.8M',
  },
  {
    id: 'yippee',
    name: 'YIPPEE! (TBH Creature)',
    color: '#1abc9c',
    darkColor: '#16a085',
    category: 'popular',
    soundUrl: '/sounds/yippee.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/yippee-sound-effect.mp3',
    chessEvent: 'pawn_promotion',
    intensity: 2,
    visualToast: 'YIPPEE!! 🎉🎊',
    description: 'German kid cola celebration cheer',
    playsCount: '15.7M',
  },
  {
    id: 'price_is_right_fail',
    name: 'Price Is Right Losing Horn',
    color: '#f39c12',
    darkColor: '#d68910',
    category: 'reactions',
    soundUrl: '/sounds/price_is_right_fail.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/price-is-right-fail.mp3',
    chessEvent: 'resignation',
    intensity: 3,
    visualToast: 'FAIL HORN 🎺📉',
    description: 'Classic game show failure tuba slides',
    playsCount: '11.4M',
  },
  {
    id: 'record_scratch',
    name: 'Record Scratch (Freeze Frame)',
    color: '#34495e',
    darkColor: '#2c3e50',
    category: 'popular',
    soundUrl: '/sounds/record_scratch.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/record-scratch.mp3',
    chessEvent: 'double_check',
    intensity: 2,
    visualToast: '*RECORD SCRATCH* ⏸️',
    description: 'Yup, that\'s me. You\'re probably wondering...',
    playsCount: '13.5M',
  },
  {
    id: 'skedaddle',
    name: 'Cartoon Skedaddle Running',
    color: '#e67e22',
    darkColor: '#d35400',
    category: 'popular',
    soundUrl: '/sounds/skedaddle.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/skedaddle.mp3',
    chessEvent: 'move_piece',
    intensity: 1,
    visualToast: 'SKEDADDLE 🏃💨',
    description: 'Bongo feet scrambling cartoon dash',
    playsCount: '9.1M',
  },
  {
    id: 'whoosh',
    name: 'Air Whoosh Fast',
    color: '#7f8c8d',
    darkColor: '#626567',
    category: 'reactions',
    soundUrl: '/sounds/whoosh.wav',
    fallbackUrl: 'https://www.myinstants.com/media/sounds/whoosh.mp3',
    chessEvent: 'move_piece',
    intensity: 1,
    visualToast: 'WHOOSH 🌪️',
    description: 'Quick cinematic transition swish',
    playsCount: '7.9M',
  },
  {
    id: 'roblox_oof',
    name: 'Roblox OOF (Death)',
    color: '#f1c40f',
    darkColor: '#f39c12',
    category: 'gaming',
    soundUrl: '/sounds/bone_crack.wav',
    fallbackUrl: '/sounds/minecraft_hurt.wav',
    chessEvent: 'capture_pawn',
    intensity: 2,
    visualToast: 'ROBLOX OOF 💀',
    description: 'The legendary death sound',
    playsCount: '21.2M',
  },
  {
    id: 'sad_violin',
    name: 'Sad Violin (Meme)',
    color: '#9b59b6',
    darkColor: '#8e44ad',
    category: 'music',
    soundUrl: '/sounds/price_is_right_fail.wav',
    fallbackUrl: '/sounds/spongebob_fail.wav',
    chessEvent: 'catastrophic_blunder',
    intensity: 3,
    visualToast: 'SAD VIOLIN 🎻😭',
    description: 'Mournful weeping string melody',
    playsCount: '15.6M',
  },
  {
    id: 'taco_bell',
    name: 'Taco Bell Bong',
    color: '#9b59b6',
    darkColor: '#8e44ad',
    category: 'popular',
    soundUrl: '/sounds/ding.wav',
    fallbackUrl: '/sounds/dramatic_boomer.wav',
    chessEvent: 'capture_rook',
    intensity: 2,
    visualToast: 'TACO BELL BONG 🔔🌮',
    description: 'Deep resonant gong impact',
    playsCount: '11.3M',
  },
  {
    id: 'airhorn',
    name: 'MLG Airhorn',
    color: '#e67e22',
    darkColor: '#d35400',
    category: 'gaming',
    soundUrl: '/sounds/dramatic_boomer.wav',
    fallbackUrl: '/sounds/triggered.wav',
    chessEvent: 'brilliant',
    intensity: 3,
    visualToast: 'MLG AIRHORN 🎺🎺🎺',
    description: 'Triple brass hype blast',
    playsCount: '19.9M',
  },
  {
    id: 'fbi_open_up',
    name: 'FBI OPEN UP!',
    color: '#1abc9c',
    darkColor: '#16a085',
    category: 'reactions',
    soundUrl: '/sounds/omg_hell_nah.wav',
    fallbackUrl: '/sounds/wilhelm_scream.wav',
    chessEvent: 'check',
    intensity: 3,
    visualToast: 'FBI OPEN UP! 🚨🚪',
    description: 'Door kick breach + police siren yell',
    playsCount: '13.8M',
  },
  {
    id: 'coffin_dance',
    name: 'Coffin Dance (Astronomia)',
    color: '#2c3e50',
    darkColor: '#1a252f',
    category: 'music',
    soundUrl: '/sounds/yippee.wav',
    fallbackUrl: '/sounds/illuminati_confirmed.wav',
    chessEvent: 'checkmate',
    intensity: 4,
    visualToast: 'COFFIN DANCE ⚰️🕺',
    description: 'The funeral dance EDM synth drop',
    playsCount: '17.2M',
  },
  {
    id: 'curb_theme',
    name: 'Directed by Robert B. Weide',
    color: '#34495e',
    darkColor: '#2c3e50',
    category: 'music',
    soundUrl: '/sounds/price_is_right_fail.wav',
    fallbackUrl: '/sounds/spongebob_fail.wav',
    chessEvent: 'resignation',
    intensity: 3,
    visualToast: 'DIRECTED BY ROBERT B. WEIDE 🎬',
    description: 'Curb Your Enthusiasm comedy credits tuba',
    playsCount: '14.1M',
  },
  {
    id: 'run_meme',
    name: 'RUN (AWOLNATION)',
    color: '#e74c3c',
    darkColor: '#c0392b',
    category: 'music',
    soundUrl: '/sounds/skedaddle.wav',
    fallbackUrl: '/sounds/whoosh.wav',
    chessEvent: 'double_check',
    intensity: 4,
    visualToast: 'RUN!! 🏃‍♂️💨',
    description: 'Electronic arpeggio into massive drop',
    playsCount: '10.8M',
  },
  {
    id: 'siuuu',
    name: 'Cristiano Ronaldo - SIUUU',
    color: '#3498db',
    darkColor: '#2980b9',
    category: 'popular',
    soundUrl: '/sounds/yippee.wav',
    fallbackUrl: '/sounds/anime_wow.wav',
    chessEvent: 'capture_queen',
    intensity: 3,
    visualToast: 'SIUUUUUU!! ⚡🔥',
    description: 'Ronaldo celebratory stadium power roar',
    playsCount: '16.8M',
  },
  {
    id: 'he_needs_some_milk',
    name: 'He Needs Some Milk!',
    color: '#ecf0f1',
    darkColor: '#bdc3c7',
    category: 'reactions',
    soundUrl: '/sounds/omg_hell_nah.wav',
    fallbackUrl: '/sounds/oh_my_god_vine.wav',
    chessEvent: 'blunder',
    intensity: 3,
    visualToast: 'HE NEED SOME MILK!! 🥛💀',
    description: 'Urgent vocal plea for blunder moves',
    playsCount: '9.8M',
  },
  {
    id: 'fat_cat_huh',
    name: 'Fat Cat Huh',
    color: '#f39c12',
    darkColor: '#d68910',
    category: 'reactions',
    soundUrl: '/sounds/sanctuary_guardian_what.wav',
    fallbackUrl: '/sounds/record_scratch.wav',
    chessEvent: 'inaccuracy',
    intensity: 2,
    visualToast: 'FAT CAT: HUH?! 🐱❓',
    description: 'The viral questioning bewildered cat',
    playsCount: '13.4M',
  },
  {
    id: 'bonk_doge',
    name: 'Bonk Doge',
    color: '#e67e22',
    darkColor: '#d35400',
    category: 'popular',
    soundUrl: '/sounds/bone_crack.wav',
    fallbackUrl: '/sounds/minecraft_hurt.wav',
    chessEvent: 'capture_minor',
    intensity: 2,
    visualToast: 'BONK! 🐕🔨',
    description: 'Cheems doge wooden bat resonant bonk',
    playsCount: '10.5M',
  },
  {
    id: 'nani',
    name: 'Omae Wa Mou Shindeiru (NANI?!)',
    color: '#e74c3c',
    darkColor: '#c0392b',
    category: 'anime',
    soundUrl: '/sounds/anime_wow.wav',
    fallbackUrl: '/sounds/triggered.wav',
    chessEvent: 'checkmate',
    intensity: 4,
    visualToast: 'NANI?! ⚡👁️',
    description: 'Anime laser eye-flash + screaming NANI?! stinger',
    playsCount: '15.3M',
  },
  {
    id: 'no_god_please_no',
    name: 'NO GOD PLEASE NO! (The Office)',
    color: '#d35400',
    darkColor: '#ba4a00',
    category: 'reactions',
    soundUrl: '/sounds/wilhelm_scream.wav',
    fallbackUrl: '/sounds/omg_hell_nah.wav',
    chessEvent: 'queen_lost',
    intensity: 4,
    visualToast: 'NO GOD PLEASE NO!! 😱',
    description: 'Michael Scott mounting panic scream',
    playsCount: '10.2M',
  },
];
